### ISSUE TITLE
Mapping Keywords

### ISSUE THREAD

**Issue by jduss4** [CDRH/api#16]
At the moment, PUTting this mapping
```
properties:
  cdrh-identifier:
    type: keyword
  dc-identifier:
    type: keyword
  cdrh-shortname:
    type: keyword
```

But the fields are coming out looking much differently

```
"cdrh-identifier": {
    "fields": {
        "keyword": {
            "ignore_above": 256,
            "type": "keyword"
        }
    },
    "type": "text"
},
```

This means that when sorting or aggregating, you have to append `.keyword` onto the end of the fieldname.  It annoys me.  Also I wonder if the filter matching is doing a lot more work because it thinks the fields are text fields.

Look into mappings and how to do correctly.
